#! /usr/bin/env python
import subprocess, time


class GPUCommunicationException(Exception):
    pass


def query_gpu():
    """
    Query the working of the gpu.

    """

    # line 80 - Compute mode
    linesToPrint = [ 79, 80, 81 ]

    while 1:
        try:
            out, err = subprocess.Popen( ["/usr/bin/nvidia-smi", "-q"]
                                         , stdout=subprocess.PIPE )\
                                 .communicate()
        except:
            raise GPUCommunicationException("Could not connect to the nvidia card.")

        out_lines = out.split('\n')

        print('\n'.join([out_lines[lineNb] for lineNb in linesToPrint]))
        print("\033[12A")

        time.sleep(1)


query_gpu()
