#! /usr/bin/env python
import subprocess
import time


class GPUCommunicationException(Exception):
    pass


def query_gpu():
    """ Query the working of the gpu. Prints out utilization and memory demands every second.
    """

    COMMAND_LINE = '/usr/bin/nvidia-smi'

    # line 80 - Compute mode
    lines_to_print = [ 79, 80, 81 ]

    while 1:
        try:
            out, err = subprocess.Popen( [COMMAND_LINE, "-q"], stdout=subprocess.PIPE )\
                                 .communicate()
        except Exception as e:
            raise GPUCommunicationException("Could not connect to the nvidia card. Error: {0}.".format(e))

        out_lines = out.split('\n')

        print('\n'.join([out_lines[line_nb] for line_nb in lines_to_print]))
        print("\033[12A")

        time.sleep(1)


query_gpu()
